### PR TITLE
Update README with the new project name/URL

### PR DESCRIPTION
**Pull request by julik**
I have undertaken a friendly fork of zip_tricks, this updates the README with the new project URL.

### CODE REVIEW

**Comment by julik** [comment]
@grdw  to you the honor!

**Review by pcriv — DISMISSED** [review]

**Review by grdw — APPROVED** [review]

**Comment by julik** [comment]
Would love to see this merged, gents! ❤️

**Comment by idanci** [comment]
> Would love to see this merged, gents! ❤️

Can you sign your commit? Policy prevents merging this PR

**Comment by julik** [comment]
> Can you sign your commit? Policy prevents merging this PR

Done!

**Review by pcriv — DISMISSED** [review]

**Review by grdw — APPROVED** [review]

**Review by isabellabrookes — APPROVED** [review]

**Comment by isabellabrookes** [comment]
@julik In order to merge, all commits in the history need to be signed. Only `153c9e3308c311b27d397d4497fe4754e6cfbac7` is thus far. Also hi! 👋🏽

**Review by pcriv — APPROVED** [review]

**Pull request merged**
