### PR TITLE
Fix unused var in EMPTY_DIRECTORY_EXTERNAL_ATTRS

### PR DESCRIPTION
**Pull request by felixbuenemann**
This fixes a problem in `ZipTricks::ZipWriter::EMPTY_DIRECTORY_EXTERNAL_ATTRS` where `file_type_dir` is defined inside the begin/end block, but `file_type_file` from the definition of `DEFAULT_EXTERNAL_ATTRS` is used.

This causes the specs to fail, so either the current code was right but misleading or the specs test for the wrong behavior.

I don't know which one is right, so I'm submitting this with failing tests.

### CODE REVIEW

**Comment by julik** [comment]
This I need to test by making an archive with some directories, I will get back to this.

**Comment by julik** [comment]
@bermannoah this was your feature - can you verify that with the dir attributes i.e. ArchiveUtility still unzips an empty directory correctly?

**Comment by bermannoah** [comment]
@julik ArchiveUtility and The Unarchiver both unzip an empty dir correctly. :)

**Comment by julik** [comment]
@bermannoah with the proposed changes in this PR applied or without? If the former is the case, can you also change the test assertions, format and merge pls?

**Pull request merged**
