### PR TITLE
Rubocop cleanup

### PR DESCRIPTION
**Pull request by julik**
I've reenabled the Rubocop task and enabled cops which make sense for zip_writer.rb.
I _think_ it makes sense not to police the tests, but maybe I'm kinda winging this one?..

### CODE REVIEW

**Comment by bermannoah** [comment]
Going to see if I can get rubocop working on travis, otherwise 👍

**Comment by bermannoah** [comment]
Nevermind, Travis is weird. :|

**Comment by bermannoah** [comment]
Pending completion of the other builds I think we've got rubocop rubocopping on Travis now. 🎉  Had to exclude the `vendor` directory.

**Comment by julik** [comment]
@davidenko87 ?

**Pull request merged**
